# Generated by Django 3.2 on 2021-11-15 19:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration"""

    initial = True

    dependencies = [
        ("core_main_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "core_composer_app",
                "permissions": (
                    ("access_composer", "Can access composer"),
                    ("save_template", "Can save template"),
                    ("save_type", "Can save type"),
                ),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "template_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core_main_app.template",
                    ),
                ),
                ("is_complex", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            bases=("core_main_app.template",),
        ),
        migrations.CreateModel(
            name="TypeVersionManager",
            fields=[
                (
                    "templateversionmanager_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core_main_app.templateversionmanager",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core_main_app.templateversionmanager",),
        ),
        migrations.CreateModel(
            name="Bucket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200, unique=True)),
                (
                    "color",
                    models.CharField(default=None, max_length=7, unique=True),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        blank=True,
                        default=[],
                        to="core_composer_app.TypeVersionManager",
                    ),
                ),
            ],
        ),
    ]
